/**
 * Created by Yeiniel Alfonso on 10/25/2017.
 */
var obj = {
    "id": "109",
    "listing_id": "9",
    "client_id": "47",
    "account_number": "dfdsf",
    "account_month_expire": "2",
    "account_year_expire": "2018",
    "client_first_name": "dsd",
    "client_last_name": "dsd",
    "client_email": "ds@df",
    "client_city": "dfr",
    "client_phone": "fsd",
    "client_reason": "leisure",
    "client_special_request": "",
    "price": "38.00",
    "count_persons": "1",
    "start_date": "2017-11-08",
    "end_date": "2017-11-10",
    "status": "created",
    "childs": "0",
    "ask_review": "0",
    "created_at": "2017-10-18 12:26 AM",
    "updated_at": "2017-10-17 18:26:58",
    "client": {
        "id": "47",
        "email": "a@a.com",
        "bank_account_id": "",
        "bank_account_number": "",
        "hotel_name": "Asas",
        "hotel_rating": "4",
        "hotel_resume_en": "",
        "hotel_resume_es": "",
        "hotel_id": "0000000001T",
        "stop_sales": "0",
        "dni": "0000000D",
        "first_name": "aaa",
        "last_name": "aaa",
        "phone": "12345678988",
        "phone_emergency": "16546516145",
        "country_code": "ES",
        "region": "Murcia",
        "city": "Burgos",
        "zip_code": "09005",
        "time_zone": "Europe/Madrid",
        "latitude": "232.234",
        "longitude": "234.324",
        "about_me": "null",
        "cancel_term_id": "1",
        "cancel_prev_cost_id": "1",
        "cancel_total_cost_id": "1",
        "file_id_type": "dni",
        "verification_id_status": "approved",
        "facebook": "",
        "google": "",
        "role": "owner",
        "created_at": "2017-08-30 01:19:13",
        "updated_at": "2017-10-12 19:08:41",
        "image_profile": "http://localhost/api//files/users/profile_default.png?t=459",
        "image_dni": null,
        "country": {
            "code": "ES",
            "name_en": "Spain",
            "name_es": "España",
            "local_name": "España",
            "lang": "es",
            "name": "España"
        },
        "bank_account": null,
        "cancel_term": {
            "id": "1",
            "name_fr": "a",
            "name_gr": "a",
            "name_en": "before 18:00 of arive day",
            "name_es": "hasta la 18:00 del día de llegada",
            "name": "hasta la 18:00 del día de llegada"
        },
        "cancel_prev_cost": {
            "id": "1",
            "name_fr": "La primera noche",
            "name_gr": "La primera noche",
            "name_en": "The first nigth",
            "name_es": "La primera noche",
            "name": "La primera noche"
        },
        "cancel_total_cost": {
            "id": "1",
            "name_fr": "igual que el cargo de cancelación",
            "name_gr": "igual que el cargo de cancelación",
            "name_en": "same as cancel charge",
            "name_es": "igual que el cargo de cancelación",
            "name": "igual que el cargo de cancelación"
        },
        "termns": "El cliente puede cancelar la reserva de forma gratuita hasta la 18:00 del día de llegada.El cliente tendrá que pagar La primera noche si cancela durante los la 18:00 del día de llegada .Si el cliente no se presenta tendrá que pagar igual que el cargo de cancelación",
        "not_verificated": false,
        "is_editable": true,
        "hotel_resume": ""
    },
    "listing": {
        "id": "9",
        "owner_id": "17",
        "listing_category_id": "2",
        "listing_type_id": "4",
        "title": "",
        "country_code": "ES",
        "city": "Ávila",
        "price": "19",
        "video_youtube": "",
        "video_vimeo": "",
        "description_es": "El Hostal Mirador de Ávila se encuentra junto a los 4 Postes, y a 100 metros de las Murallas. Es un hostal económico y agradable de ambiente familiar. La limpieza y la higiene, están garantizados. Las habitaciones son exteriores, de reciente construcción, amplias y confortables. Todas disponen servicios individuales con útiles de aseo. Calefacción y aire acondicionado, mesa escritorio y armario, TV. LCD, y WIFI gratis las 24h. Salón social donde se puede desayunar. Con aire acondicionado. TV. Video, Internet y juegos de mesa. Desde las habitaciones, se divisa. El Humilladero de los 4 Postes, La Universidad Católica, Palacio de Congresos y las murallas. Vistas de la muralla, palacio,...Vistas desde las habitaciones Su entorno, con las mejores vistas panorámicas de la Ciudad. La ermita de San segundo. Buenos restaurantes típicos, donde podrá degustar la gastronomía local. Podrá practicar senderismo y bicicleta. Y si lo desea, podemos recomendarle las mejores excursiones, rutas o zonas de interés turístico. Disponemos de amplia zona de estacionamiento gratuito, también privado. Bien comunicado en todas direcciones. Madrid 112 Km. Segovia 60 Km. Salamanca 88 Km. Toledo 130. Valladolid 125 Km. Fiestas Patronales. \r\n\r\nEl 2 de Mayo San segundo, patrón de la Ciudad. 2ª quincena de Julio, fiestas de Verano. 1ª de Septiembre, Gran Mercado medieval. \r\n\r\nEl 15 de Octubre fiesta Grande. Santa Teresa de Jesús.",
        "description_en": "Hostal Mirador de Ávila, along with 4 Postes, and 100 meters from the Walls.\r\n\r\nIt is a budget friendly family atmosphere guesthouse. Cleanliness and hygiene are guaranteed.\r\n\r\nThe rooms are exterior, newly built, spacious and comfortable. All have individual services with useful amenities. Heating and air conditioning, desk, wardrobe, TV. LCD, free WIFI and 24h.\r\n\r\nSocial lounge where you can have breakfast. With air conditioning. TV. Video, Internet and games.\r\n\r\nFrom the rooms, can be seen. The Humilladero of 4 Poles, Catholic University, Congress and the walls.\r\n\r\nVistas de la muralla, palacio,...Vistas desde las habitaciones\r\n\r\nViews of the wall, castle, ... View from room\r\n\r\nIts setting, with the best panoramic views of the City. The hermitage of San second. Buenos typical restaurants where you can sample the local cuisine.\r\n\r\nYou can go hiking and biking. And if you wish, we can recommend the best tours, routes or areas of interest.\r\n\r\nWe have plenty of complimentary parking, also private. Well connected in all directions. Madrid Segovia 112 Km 60 Km 88 Km Toledo Salamanca 130. Valladolid 125 Km\r\n\r\nFestivities. \r\n\r\nOn May 2 San second pattern of the City. 2nd half of July, Summer holidays. September 1st, Great Medieval market. \r\n\r\nThe October 15 celebration Grande. Saint Teresa of Jesus.",
        "longitude": "-4.711762700000008",
        "latitude": "40.6584389",
        "status": "draft",
        "relevant": "0",
        "close_sales": "0",
        "created_at": "2017-05-17 11:26:09",
        "updated_at": "2017-05-24 06:11:50",
        "owner": {
            "id": "17",
            "email": "miradordeavila@hotmail.com",
            "bank_account_id": "",
            "bank_account_number": "",
            "hotel_name": "HOSTAL MIRADOR DE AVILA",
            "hotel_rating": "2",
            "hotel_resume_en": "",
            "hotel_resume_es": "",
            "hotel_id": "6522785P",
            "stop_sales": "0",
            "dni": "06522785P",
            "first_name": "Julia",
            "last_name": "Padilla Caballero",
            "phone": "34920226265",
            "phone_emergency": "34920226265",
            "country_code": "ES",
            "region": "Castille and León",
            "city": "Ávila",
            "zip_code": "05001",
            "time_zone": "Europe/Madrid",
            "latitude": "40.6572",
            "longitude": "-4.6996",
            "about_me": "null",
            "cancel_term_id": "4",
            "cancel_prev_cost_id": "1",
            "cancel_total_cost_id": "1",
            "file_id_type": "dni",
            "verification_id_status": "approved",
            "facebook": "",
            "google": "",
            "role": "owner",
            "created_at": "2017-05-09 04:58:50",
            "updated_at": "2017-05-17 12:26:41",
            "image_profile": "http://localhost/api//files/users/profile_default.png?t=697",
            "image_dni": null,
            "country": {
                "code": "ES",
                "name_en": "Spain",
                "name_es": "España",
                "local_name": "España",
                "lang": "es",
                "name": "España"
            },
            "bank_account": null,
            "cancel_term": {
                "id": "4",
                "name_fr": "a",
                "name_gr": "a",
                "name_en": "2 days before arrive day",
                "name_es": "hasta 2 día antes del dia de llegada",
                "name": "hasta 2 día antes del dia de llegada"
            },
            "cancel_prev_cost": {
                "id": "1",
                "name_fr": "La primera noche",
                "name_gr": "La primera noche",
                "name_en": "The first nigth",
                "name_es": "La primera noche",
                "name": "La primera noche"
            },
            "cancel_total_cost": {
                "id": "1",
                "name_fr": "igual que el cargo de cancelación",
                "name_gr": "igual que el cargo de cancelación",
                "name_en": "same as cancel charge",
                "name_es": "igual que el cargo de cancelación",
                "name": "igual que el cargo de cancelación"
            },
            "termns": "El cliente puede cancelar la reserva de forma gratuita hasta 2 día antes del dia de llegada.El cliente tendrá que pagar La primera noche si cancela durante los 2 día antes del dia de llegada .Si el cliente no se presenta tendrá que pagar igual que el cargo de cancelación",
            "not_verificated": false,
            "is_editable": false,
            "hotel_resume": ""
        },
        "listing_category": {
            "id": "2",
            "name_fr": "Hostel o Pensión",
            "name_gr": "Hostel o Pensión",
            "name_en": "HOSTEL:..",
            "name_es": "HOSTEL:..",
            "listing_types": [{
                "id": "3",
                "listing_category_id": "2",
                "name_fr": "Estándar 2 camas privadas",
                "name_gr": "Estándar 2 camas privadas",
                "name_en": "STANDARD 2 PRIVATE BEDS 29€",
                "name_es": "ESTÁNDAR 2 CAMAS PRIVADAS 29€",
                "price": "29",
                "name": "ESTÁNDAR 2 CAMAS PRIVADAS 29€",
                "category": {
                    "id": "2",
                    "name_fr": "Hostel o Pensión",
                    "name_gr": "Hostel o Pensión",
                    "name_en": "HOSTEL:..",
                    "name_es": "HOSTEL:..",
                    "name": "HOSTEL:.."
                }
            }, {
                "id": "4",
                "listing_category_id": "2",
                "name_fr": "Estándar camas Dormitorio Mixto",
                "name_gr": "Estándar camas Dormitorio Mixto",
                "name_en": "STANDARD ROOM - MIXED ROOM 19€",
                "name_es": "HABITACIÓN ESTÁNDAR - HABITACIÓN MIXTA 19€",
                "price": "19",
                "name": "HABITACIÓN ESTÁNDAR - HABITACIÓN MIXTA 19€",
                "category": {
                    "id": "2",
                    "name_fr": "Hostel o Pensión",
                    "name_gr": "Hostel o Pensión",
                    "name_en": "HOSTEL:..",
                    "name_es": "HOSTEL:..",
                    "name": "HOSTEL:.."
                }
            }, {
                "id": "5",
                "listing_category_id": "2",
                "name_fr": "Estándar camas Dormitorio Femenino",
                "name_gr": "Estándar camas Dormitorio Femenino",
                "name_en": "SATANDARD ROOM - FEMALE ROOM 19€",
                "name_es": "HABITACIÓN ESTÁNDAR - DORMITORIO FEMENINO 19€",
                "price": "19",
                "name": "HABITACIÓN ESTÁNDAR - DORMITORIO FEMENINO 19€",
                "category": {
                    "id": "2",
                    "name_fr": "Hostel o Pensión",
                    "name_gr": "Hostel o Pensión",
                    "name_en": "HOSTEL:..",
                    "name_es": "HOSTEL:..",
                    "name": "HOSTEL:.."
                }
            }, {
                "id": "12",
                "listing_category_id": "2",
                "name_fr": "",
                "name_gr": "",
                "name_en": "DOUBLE STANDARD ROOM - MIXED ROOM 24€",
                "name_es": "DOBLE HABITACIÓN ESTÁNDAR - HABITACIÓN MIXTA 24€",
                "price": "24",
                "name": "DOBLE HABITACIÓN ESTÁNDAR - HABITACIÓN MIXTA 24€",
                "category": {
                    "id": "2",
                    "name_fr": "Hostel o Pensión",
                    "name_gr": "Hostel o Pensión",
                    "name_en": "HOSTEL:..",
                    "name_es": "HOSTEL:..",
                    "name": "HOSTEL:.."
                }
            }, {
                "id": "22",
                "listing_category_id": "2",
                "name_fr": "",
                "name_gr": "",
                "name_en": "STANDERD 2 PRIVATE BEDS 39€",
                "name_es": "HABITACIÓN ESTÁNDAR 2 CAMAS PRIVADAS 39€",
                "price": "39",
                "name": "HABITACIÓN ESTÁNDAR 2 CAMAS PRIVADAS 39€",
                "category": {
                    "id": "2",
                    "name_fr": "Hostel o Pensión",
                    "name_gr": "Hostel o Pensión",
                    "name_en": "HOSTEL:..",
                    "name_es": "HOSTEL:..",
                    "name": "HOSTEL:.."
                }
            }],
            "name": "HOSTEL:.."
        },
        "listing_type": {
            "id": "4",
            "listing_category_id": "2",
            "name_fr": "Estándar camas Dormitorio Mixto",
            "name_gr": "Estándar camas Dormitorio Mixto",
            "name_en": "STANDARD ROOM - MIXED ROOM 19€",
            "name_es": "HABITACIÓN ESTÁNDAR - HABITACIÓN MIXTA 19€",
            "price": "19",
            "name": "HABITACIÓN ESTÁNDAR - HABITACIÓN MIXTA 19€",
            "category": {
                "id": "2",
                "name_fr": "Hostel o Pensión",
                "name_gr": "Hostel o Pensión",
                "name_en": "HOSTEL:..",
                "name_es": "HOSTEL:..",
                "name": "HOSTEL:.."
            }
        },
        "country": {
            "code": "ES",
            "name_en": "Spain",
            "name_es": "España",
            "local_name": "España",
            "lang": "es",
            "name": "España"
        },
        "images": [{
            "id": "32",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063412.jpg?t=405",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "33",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063444.jpg?t=763",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "34",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063633.jpg?t=785",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "35",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063653.jpg?t=346",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "36",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063659.jpg?t=411",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "37",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063730.jpg?t=951",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "38",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063863.jpg?t=575",
            "is_primary": true,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "39",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063897.jpg?t=510",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "40",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063939.jpg?t=39",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "41",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14064014.jpg?t=50",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:48",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "42",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/26849804.jpg?t=785",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:48",
            "updated_at": "2017-05-24 06:11:50"
        }, {
            "id": "43",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/31842688.jpg?t=444",
            "is_primary": false,
            "created_at": "2017-05-18 07:53:48",
            "updated_at": "2017-05-24 06:11:50"
        }],
        "stopped_sales_dates": [],
        "image_primary": {
            "id": "38",
            "listing_id": "9",
            "caption": "",
            "path": "http://localhost/api/files/listings/9/14063863.jpg?t=760",
            "is_primary": true,
            "created_at": "2017-05-18 07:53:47",
            "updated_at": "2017-05-24 06:11:50"
        },
        "services": [{
            "id": "1",
            "name_es": "Agua caliente",
            "name_en": "Watter hot",
            "name_gr": "",
            "name_fr": "Calent ague",
            "description_es": "Agua en la ducha",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Agua caliente"
        }, {
            "id": "2",
            "name_es": "Parking (De pago)",
            "name_en": "Parking (Payable)",
            "name_gr": "",
            "name_fr": "Prquet",
            "description_es": "Servicio de parqueo",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Parking (De pago)"
        }, {
            "id": "13",
            "name_es": "Desayuno disponible (de pago)",
            "name_en": "Breakfast (Payable)",
            "name_gr": "",
            "name_fr": "Breakfast",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Desayuno disponible (de pago)"
        }, {
            "id": "16",
            "name_es": "TV por satélite",
            "name_en": "Cable TV",
            "name_gr": "",
            "name_fr": "Cable TV",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "TV por satélite"
        }, {
            "id": "17",
            "name_es": "Parking gratuito incluido",
            "name_en": "Free parking on premises",
            "name_gr": "",
            "name_fr": "Free parking on premises",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Parking gratuito incluido"
        }, {
            "id": "21",
            "name_es": "Secador de pelo",
            "name_en": "Hair dryer",
            "name_gr": "",
            "name_fr": "Hair dryer",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Secador de pelo"
        }, {
            "id": "23",
            "name_es": "Perchas",
            "name_en": "Hangers",
            "name_gr": "",
            "name_fr": "Hangers",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Perchas"
        }, {
            "id": "24",
            "name_es": "Televisión",
            "name_en": "TV",
            "name_gr": "",
            "name_fr": "TV",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Televisión"
        }, {
            "id": "25",
            "name_es": "Apto para familias y niños",
            "name_en": "Family/kid friendly",
            "name_gr": "",
            "name_fr": "Family/kid friendly",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Apto para familias y niños"
        }, {
            "id": "26",
            "name_es": "Calefacción",
            "name_en": "Heating",
            "name_gr": "",
            "name_fr": "Heating",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Calefacción"
        }, {
            "id": "27",
            "name_es": "Elementos básicos",
            "name_en": "Essentials",
            "name_gr": "",
            "name_fr": "Essentials",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Elementos básicos"
        }, {
            "id": "28",
            "name_es": "Internet",
            "name_en": "Internet",
            "name_gr": "",
            "name_fr": "Internet",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Internet"
        }, {
            "id": "31",
            "name_es": "Internet inalámbrico (wifi)",
            "name_en": "Wireless Internet",
            "name_gr": "",
            "name_fr": "Wireless Internet",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Internet inalámbrico (wifi)"
        }, {
            "id": "36",
            "name_es": "Recepción disponible las 24 horas",
            "name_en": "Reception Area 24 hours available",
            "name_gr": "",
            "name_fr": "",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Recepción disponible las 24 horas"
        }, {
            "id": "45",
            "name_es": "Cunas o camas infantiles GRATIS",
            "name_en": "Baby cot free of charge",
            "name_gr": "",
            "name_fr": "",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Cunas o camas infantiles GRATIS"
        }, {
            "id": "47",
            "name_es": "Camas supletorias (de Pago)",
            "name_en": "Rollaway Beds (Payable)",
            "name_gr": "",
            "name_fr": "",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Camas supletorias (de Pago)"
        }, {
            "id": "50",
            "name_es": "Productos de higiene personal GRATIS",
            "name_en": "Free toiletries",
            "name_gr": "",
            "name_fr": "",
            "description_es": "",
            "description_en": "",
            "description_gr": "",
            "description_fr": "",
            "name": "Productos de higiene personal GRATIS"
        }],
        "rating": 0,
        "reviews_total": 0,
        "comments_total": 0,
        "is_verificated": true,
        "description": "El Hostal Mirador de Ávila se encuentra junto a los 4 Postes, y a 100 metros de las Murallas. Es un hostal económico y agradable de ambiente familiar. La limpieza y la higiene, están garantizados. Las habitaciones son exteriores, de reciente construcción, amplias y confortables. Todas disponen servicios individuales con útiles de aseo. Calefacción y aire acondicionado, mesa escritorio y armario, TV. LCD, y WIFI gratis las 24h. Salón social donde se puede desayunar. Con aire acondicionado. TV. Video, Internet y juegos de mesa. Desde las habitaciones, se divisa. El Humilladero de los 4 Postes, La Universidad Católica, Palacio de Congresos y las murallas. Vistas de la muralla, palacio,...Vistas desde las habitaciones Su entorno, con las mejores vistas panorámicas de la Ciudad. La ermita de San segundo. Buenos restaurantes típicos, donde podrá degustar la gastronomía local. Podrá practicar senderismo y bicicleta. Y si lo desea, podemos recomendarle las mejores excursiones, rutas o zonas de interés turístico. Disponemos de amplia zona de estacionamiento gratuito, también privado. Bien comunicado en todas direcciones. Madrid 112 Km. Segovia 60 Km. Salamanca 88 Km. Toledo 130. Valladolid 125 Km. Fiestas Patronales. \r\n\r\nEl 2 de Mayo San segundo, patrón de la Ciudad. 2ª quincena de Julio, fiestas de Verano. 1ª de Septiembre, Gran Mercado medieval. \r\n\r\nEl 15 de Octubre fiesta Grande. Santa Teresa de Jesús.",
        "is_editable": false
    },
    "bank_account": null
}