'use strict';


angular.module('app', [
    'ngAnimate',
    'ngAria',
    'ngCookies',
    'ngSanitize',
    'ngTouch',
    'ngStorage',
    'ui.router',
    'ui.bootstrap',
    'ui.utils',
    'ui.load',
    'ui.jq',
    // 'oc.lazyLoad',
    'pascalprecht.translate',
    'toaster',
    'angular-jwt',
    'angular-storage',
    'angular-loading-bar',
    'ngTable',
    'textAngular',
    'videosharing-embed',
    'ngEmoticons',
    'angular-scroll-animate',
    'socialLogin',
    'ngFileUpload',
    'ui.utils.masks',
    'angularMoment',
    'ngMap',
    'angular-preload-image',
    '720kb.socialshare',
    '720kb.datepicker',
    'ui.calendar',
    'truncate',
    'ui.bootstrap.datetimepicker',
    'smart-table'
]);
